package raylib;

enum abstract KeyboardKey(Int) from Int to Int {
	var KEY_NULL = 0; // Key: NULL, used for no key pressed
	// Alphanumeric keys
	var KEY_APOSTROPHE = 39; // Key: '
	var KEY_COMMA = 44; // Key: ,
	var KEY_MINUS = 45; // Key: -
	var KEY_PERIOD = 46; // Key: .
	var KEY_SLASH = 47; // Key: /
	var KEY_ZERO = 48; // Key: 0
	var KEY_ONE = 49; // Key: 1
	var KEY_TWO = 50; // Key: 2
	var KEY_THREE = 51; // Key: 3
	var KEY_FOUR = 52; // Key: 4
	var KEY_FIVE = 53; // Key: 5
	var KEY_SIX = 54; // Key: 6
	var KEY_SEVEN = 55; // Key: 7
	var KEY_EIGHT = 56; // Key: 8
	var KEY_NINE = 57; // Key: 9
	var KEY_SEMICOLON = 59; // Key: ;
	var KEY_EQUAL = 61; // Key: =
	var KEY_A = 65; // Key: A | a
	var KEY_B = 66; // Key: B | b
	var KEY_C = 67; // Key: C | c
	var KEY_D = 68; // Key: D | d
	var KEY_E = 69; // Key: E | e
	var KEY_F = 70; // Key: F | f
	var KEY_G = 71; // Key: G | g
	var KEY_H = 72; // Key: H | h
	var KEY_I = 73; // Key: I | i
	var KEY_J = 74; // Key: J | j
	var KEY_K = 75; // Key: K | k
	var KEY_L = 76; // Key: L | l
	var KEY_M = 77; // Key: M | m
	var KEY_N = 78; // Key: N | n
	var KEY_O = 79; // Key: O | o
	var KEY_P = 80; // Key: P | p
	var KEY_Q = 81; // Key: Q | q
	var KEY_R = 82; // Key: R | r
	var KEY_S = 83; // Key: S | s
	var KEY_T = 84; // Key: T | t
	var KEY_U = 85; // Key: U | u
	var KEY_V = 86; // Key: V | v
	var KEY_W = 87; // Key: W | w
	var KEY_X = 88; // Key: X | x
	var KEY_Y = 89; // Key: Y | y
	var KEY_Z = 90; // Key: Z | z
	var KEY_LEFT_BRACKET = 91; // Key: [
	var KEY_BACKSLASH = 92; // Key: '\'
	var KEY_RIGHT_BRACKET = 93; // Key: ]
	var KEY_GRAVE = 96; // Key: `
	// Function keys
	var KEY_SPACE = 32; // Key: Space
	var KEY_ESCAPE = 256; // Key: Esc
	var KEY_ENTER = 257; // Key: Enter
	var KEY_TAB = 258; // Key: Tab
	var KEY_BACKSPACE = 259; // Key: Backspace
	var KEY_INSERT = 260; // Key: Ins
	var KEY_DELETE = 261; // Key: Del
	var KEY_RIGHT = 262; // Key: Cursor right
	var KEY_LEFT = 263; // Key: Cursor left
	var KEY_DOWN = 264; // Key: Cursor down
	var KEY_UP = 265; // Key: Cursor up
	var KEY_PAGE_UP = 266; // Key: Page up
	var KEY_PAGE_DOWN = 267; // Key: Page down
	var KEY_HOME = 268; // Key: Home
	var KEY_END = 269; // Key: End
	var KEY_CAPS_LOCK = 280; // Key: Caps lock
	var KEY_SCROLL_LOCK = 281; // Key: Scroll down
	var KEY_NUM_LOCK = 282; // Key: Num lock
	var KEY_PRINT_SCREEN = 283; // Key: Print screen
	var KEY_PAUSE = 284; // Key: Pause
	var KEY_F1 = 290; // Key: F1
	var KEY_F2 = 291; // Key: F2
	var KEY_F3 = 292; // Key: F3
	var KEY_F4 = 293; // Key: F4
	var KEY_F5 = 294; // Key: F5
	var KEY_F6 = 295; // Key: F6
	var KEY_F7 = 296; // Key: F7
	var KEY_F8 = 297; // Key: F8
	var KEY_F9 = 298; // Key: F9
	var KEY_F10 = 299; // Key: F10
	var KEY_F11 = 300; // Key: F11
	var KEY_F12 = 301; // Key: F12
	var KEY_LEFT_SHIFT = 340; // Key: Shift left
	var KEY_LEFT_CONTROL = 341; // Key: Control left
	var KEY_LEFT_ALT = 342; // Key: Alt left
	var KEY_LEFT_SUPER = 343; // Key: Super left
	var KEY_RIGHT_SHIFT = 344; // Key: Shift right
	var KEY_RIGHT_CONTROL = 345; // Key: Control right
	var KEY_RIGHT_ALT = 346; // Key: Alt right
	var KEY_RIGHT_SUPER = 347; // Key: Super right
	var KEY_KB_MENU = 348; // Key: KB menu
	// Keypad keys
	var KEY_KP_0 = 320; // Key: Keypad 0
	var KEY_KP_1 = 321; // Key: Keypad 1
	var KEY_KP_2 = 322; // Key: Keypad 2
	var KEY_KP_3 = 323; // Key: Keypad 3
	var KEY_KP_4 = 324; // Key: Keypad 4
	var KEY_KP_5 = 325; // Key: Keypad 5
	var KEY_KP_6 = 326; // Key: Keypad 6
	var KEY_KP_7 = 327; // Key: Keypad 7
	var KEY_KP_8 = 328; // Key: Keypad 8
	var KEY_KP_9 = 329; // Key: Keypad 9
	var KEY_KP_DECIMAL = 330; // Key: Keypad .
	var KEY_KP_DIVIDE = 331; // Key: Keypad /
	var KEY_KP_MULTIPLY = 332; // Key: Keypad *
	var KEY_KP_SUBTRACT = 333; // Key: Keypad -
	var KEY_KP_ADD = 334; // Key: Keypad +
	var KEY_KP_ENTER = 335; // Key: Keypad Enter
	var KEY_KP_EQUAL = 336; // Key: Keypad =
	// Android key buttons
	var KEY_BACK = 4; // Key: Android back button
	var KEY_MENU = 5; // Key: Android menu button
	var KEY_VOLUME_UP = 24; // Key: Android volume up button
	var KEY_VOLUME_DOWN = 25; // Key: Android volume down button
}
