name: CI build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Compiling 
        run: |
          haxelib git flixel-raylib https://github.com/Vortex2Oblivion/flixel-raylib
          ./build_ndlls.bat
          cd test
          haxe build.hxml
